### PR TITLE
(feat) Add files for mock data

### PR DESCRIPTION
**Pull request by jcrben**
I've uploaded a couple users to firebase (https://careful-harmonica.firebaseio.com/). I initially thought I'd just create an object with random data and write it to a file using node but using an object literal ended up being quicker.

The data.json file also has some notes on Firebase data. The one gotcha is that dots (.) are not allowed in keys and for images we'll have to either: base64 encode our images or refer to them using data:url (see http://stackoverflow.com/questions/13955813/how-can-i-view-and-store-images-in-firebase).

### CODE REVIEW

**Comment by APTy** [comment]
This looks solid. My one question is whether we can have firebase autogenerate a user ID and then store the user's email as a key-value pair in order to avoid using a comma in the email address. That way we don't have to parse their email later.

**Comment by jcrben** [comment]
It would be great if we could avoid that and Firebase will autogenerate keys if we use push(), but we have to use these keys in our request routes and they are quite ugly and may be difficult to work with. See http://stackoverflow.com/a/14965065/4200039 where the Firebase engineer suggests using an email and parsing the comma out. Another alternative is to require people to sign up with usernames or perhaps even using integer keys, although Firebase describes that as an anti-pattern here in https://www.firebase.com/docs/web/guide/saving-data.html#section-push. If we did integer keys we might have to use transaction() to avoid overwriting.

**Comment by APTy** [comment]
:+1: I'm cool with that for now. We may even be able to use their linkedin oauth token as a unique id once we get to that point.

**Comment by ryyann** [comment]
Looks good to me.

**Pull request merged**
