### PR TITLE
Check for undefined to improve reliability

### PR DESCRIPTION
**Pull request by jcrben**
@APTy @pravipati 
In case you're putting this on your resume (I've heard Tyler is settled in the job search), I had someone who hadn't set their name try to sign up and it broke as 'undefined'. This fixes it, and is also deployed.

### CODE REVIEW

**Comment by jcrben** [comment]
Not sure about the failing tests - says the bower install failed, but as I said this change is deployed just fine. Plan to merge this tomorrow.

**Comment by APTy** [comment]
I thought deployment was hooked on the master branch. How was it deployed if this hasn't been merged yet? lol

Anyway, I'm generally fine with this, but FYI all the glyphs/icons are broken in the app now.. not sure when that happened, but oh well.

**Comment by jcrben** [comment]
Good catch. I think that's caused by [the font css file](https://github.com/careful-harmonica/careful-harmonica/blob/master/app/styles/global/_font.scss) including the cache identifiers. I think the files get a new string when there's a new build (`grunt serve:dist`). I'll look into using some sort of glob later to fix that... may not be too hard. Or if nothing else just rewrite them to match the new identifier.

As far as deployment, I just installed firebase-tools and typed firebase deploy. I think it just requires that you're a member of the firebase organization to deploy. Was sort of surprised it was so easy.

**Comment by jcrben** [comment]
Icons are back. Dunno why the `filerev` task was renaming the files and not fixing the CSS, but we don't need to worry about the caching of our static assets anyway.

**Pull request merged**
