### PR TITLE
(feat) Employer view and skeleton controller

### PR DESCRIPTION
**Pull request by jcrben**
First pass of the employer view and controller. Basically lays out Tyler's picture plus a table of jobs and their status at the bottom.

### CODE REVIEW

**Comment by APTy** [comment]
Good template, let's merge this in

**Comment by pravipati** [comment]
Ben could you add a newline to the end of the files and then resubmit the pull request? If you click on the files changed tab Github is complaining that the last line of the files don't have newline characters.

**Comment by jcrben** [comment]
Looks to be fixed, thanks!

I used git commit --amend to add that tweak into my last commit (didn't have to do a new pull request) but I did have to do a --force (git push -f origin feat/employer).

**Comment by ryyann** [comment]
Looks good to me. Merging now.

**Pull request merged**
